services:
  metabase:
    image: metabase/metabase:latest
    volumes:
      - ./include/metabase:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - 3000:3000
    restart: always

  frontend:
    build:
      context: ./docs
      dockerfile: Dockerfile
    volumes:
      - ./docs:/app
      - /app/node_modules
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
    restart: always

