services:
  metabase:
    image: metabase/metabase:latest
    volumes:
      - ./include/metabase:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - 3000:3000
    restart: always
